remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: <p align="center"> Ravi Kumar Dhiman </p>
logo: /assets/img/photo.jpg
description: 
  <p align="center">
  <a href="assets/files/resume_sophophilic.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ravi-kumar-dhiman/">LinkedIn</a> |
  <a href="https://github.com/sophophilic">GitHub</a>
  
  <br>
  Working as an Engineering Manager responsible for delivering Anti-Spam solutions 
  for enhancing the realtime Messaging capabilities and allowing only clean traffic out of the platform.
  Previously worked with Morgan Stanley, Boston Consulting Group (BCG), Deloitte etc.
  <br>
  </p>
theme: jekyll-theme-minimal
